from abc import abstractmethod, ABC
import os


def define_ast(output_dir: str, base_name: str, base_class_name: str, types: list[str]):
    os.makedirs(output_dir, exist_ok=True)

    path = f"{output_dir}/{base_name}.py"
    print(path)

    with open(path, "w") as f:
        f.write("#####################################\n")
        f.write("# GENERATED BY tool/generate_ast.py #\n")
        f.write("#####################################\n\n")
        f.write("from abc import ABC, abstractmethod\n")
        f.write("from typing import TypeVar, Generic, override\n")
        f.write("from src import *\n")
        f.write("\n\n")

        f.write('R = TypeVar("R")\n\n\n')

        f.write(f"class Visitor(ABC, Generic[R]):\n")
        for t in types:
            class_name = t.split("=")[0].strip()
            f.write(
                f'\tdef visit_{class_name.lower()}_{base_class_name.lower()}(self, {base_class_name.lower()}: "{class_name}") -> R: ...\n'
            )
        f.write("\n\n")
        f.write(f"class {base_class_name}(ABC):\n")
        f.write(f"\t@abstractmethod\n")
        f.write(f"\tdef accept(self, visitor: Visitor[R]) -> R: ...\n")
        f.write(f"\n\n")

        for t in types:
            class_name = t.split("=")[0].strip()
            fields = t.split("=")[1].strip()
            f.write(f"class {class_name}({base_class_name}):\n")
            f.write(f"\tdef __init__(self, {fields}):\n")
            field_list = fields.split(",")
            for field in field_list:
                field_name = field.split(":")[0].strip()
                f.write(f"\t\tself.{field_name} = {field_name}\n")
            f.write(f"\t\n")
            f.write(f"\t@override\n")
            f.write(f"\tdef accept(self, visitor: Visitor[R]) -> R:\n")
            f.write(
                f"\t\treturn visitor.visit_{class_name.lower()}_{base_class_name.lower()}(self)\n"
            )
            f.write("\n\n")


if __name__ == "__main__":
    types = [
        "Binary   = left: Expr, operator: Token, right: Expr",
        "Grouping = expression: Expr",
        "Literal  = value: object",
        "Unary    = operator: Token, right: Expr",
    ]
    define_ast("src", "expr", "Expr", types)
