#####################################
# GENERATED BY tool/generate_ast.py #
#####################################

from abc import ABC, abstractmethod
from typing import TypeVar, override
from src import *


R = TypeVar("R")


class StmtVisitor[R](ABC):
    @abstractmethod
    def visit_expressionstmt_stmt(self, stmt: "ExpressionStmt") -> R: ...
    @abstractmethod
    def visit_printstmt_stmt(self, stmt: "PrintStmt") -> R: ...
    @abstractmethod
    def visit_var_stmt(self, stmt: "Var") -> R: ...


class Stmt(ABC):
    @abstractmethod
    def accept(self, visitor: StmtVisitor[R]) -> R: ...


class ExpressionStmt(Stmt):
    def __init__(self, expression: Expr):
        self.expression = expression

    @override
    def accept(self, visitor: StmtVisitor[R]) -> R:
        return visitor.visit_expressionstmt_stmt(self)


class PrintStmt(Stmt):
    def __init__(self, expression: Expr):
        self.expression = expression

    @override
    def accept(self, visitor: StmtVisitor[R]) -> R:
        return visitor.visit_printstmt_stmt(self)


class Var(Stmt):
    def __init__(self, name: Token, initializer: Expr):
        self.name = name
        self.initializer = initializer

    @override
    def accept(self, visitor: StmtVisitor[R]) -> R:
        return visitor.visit_var_stmt(self)
